pangweiwei/slua

- Assets/Slua/Editor/LuaCodeGen.cs
- Assets/Slua/Script/LuaDLL.cs
- Assets/example/Custom.cs
- Assets/example/Deleg.cs
- Assets/example/HelloWorld.cs
use Attribute to judge which custom class to generate.
> use Attribute to judge which custom class to generate.

- .gitignore
- Assets/Slua/Script/LuaObject.cs
修复pushvalue 传入数组为null时的bug，增加几个常用传入数组接口
add ignore /Library and /Temp in .gitignore
> 修复pushValue，增加gitignore内容

- Assets/Slua/Editor/LuaCodeGen.cs
- Assets/Slua/Resources/custom.txt
- Assets/Slua/Script/LuaObject.cs
- Assets/Slua/Script/LuaSvr.cs
- Assets/Slua/example/Custom.cs
调整一下导出类的路径与菜单。防止误操作。。加入了this[]的导出，可以在lua通过 getItem(key) setItem(key,value)的方式调用
> 调整菜单与支持lua访问this[]

- Assets/Slua/Editor/LuaCodeGen.cs
Unity Editor needs a compile process after each "Clear" option, but before this process finished, the "Make" operations is always get old-assemblies or old-compiled codes. This gonna causing some problems. So I added a "IsCompiling" variable to verify if we could really make it.
> Add IsCompiling value into LuaCodeGen.cs

- Assets/Slua/Script/LuaDLL.cs
> Correct debug message at checkType error

- Assets/Slua/Editor/LuaCodeGen.cs
- Assets/Slua/Script/LuaObject.cs
- Assets/Slua/Script/LuaObject_overload.cs
- Assets/Slua/Script/LuaState.cs
- Assets/Slua/Script/LuaSvr.cs
1.add LuaTable::length() to get length
2.variable name support @keywords format
3.export Assets/Plugins in Assembly-CSharp-firstpass
4.GetExportedTypes() may cause exception
> bug fix and new feature

- Assets/Slua/Script/Coroutine.cs
usage:
1/ 
```lua
function LoadAssetBundleAsync(archives)
return uCoroutine.create(function()
for _, v in pairs(archives) do
uCoroutine.yield( v:DoLoad() );
end
end
end
function OnInit()
uCoroutine.create(function()
uCoroutine.yield(LoadAssetBundleAsync({prefabs1, prefabs2}))
prefabs1:LoadAsset("asset")
end)
end
```
> nested coroutine call supports

- Assets/Slua/Editor/CustomExport.cs
error fix when build android or ios
> fix unity 5.2.2f1 build error

- Assets/Slua/Editor/LuaCodeGen.cs
- Assets/Slua/Editor/SLuaSetting.cs
- Assets/Slua/Editor/SLuaSetting.cs.meta
> Add SLua setting.

- Assets/Slua/Editor/LuaCodeGen.cs
> Revert e7aee021257d243b8fff63aa5bf2a77c89aa82ed

- Assets/Slua/Editor/CustomExport.cs
- Assets/Slua/Editor/LuaCodeGen.cs
- Assets/Slua/Script/LuaSvr.cs
- Assets/Slua/Script/LuaVarObject.cs
CustomExport 添加属性  "FunctionFilterList",  让部分类中的某个函数不被生成~
主要在生成过程中"UIWidget.showHandles"是Editor only的函数，筛掉
> Function filter of Code Generator

- Assets/Slua/Editor/LuaCodeGen.cs
- build/make_win_with_2013.bat
- debugger/mac/runldb.sh
if do not find vs2013, try to find vs2012
> add build support for vs2012

- Assets/Plugins/Slua_Managed/Lua3rdDLL.cs
slua移到plugins下后，原来的`Assembly .GetExecutingAssembly()`取到的是first-pass，导致查找不到attribute。
修复了一下这个问题
> 修复attribute查找问题

- Assets/Slua/Editor/LuaCodeGen.cs
- Assets/Slua/Resources/custom.txt
function with StaticExportAttribute should not  be consider as instanceFunc
> fix custom function export

- Assets/Plugins/Slua_Managed/ObjectCache.cs
> Bugfix: ObjectCache在设备上导致Mono内存泄漏问题(#122)

- Assets/Plugins/Slua_Managed/Helper.cs
- Assets/Plugins/Slua_Managed/LuaDLL.cs
- Assets/Plugins/Slua_Managed/LuaObject_basetype.cs
It's a inverse operation of Slua.ToString.
It can convert lua binary string to c# byte[]
> Add Slua.ToBytes

- Assets/Plugins/Slua_Managed/Helper.cs
- Assets/Plugins/Slua_Managed/ObjectCache.cs
no ToBytes method in LuaObject, and ObjectCache.Equals hide Object.Equals
> fix compile warn

- Assets/Plugins/Slua_Managed/LuaValueType.cs
> LuaValueType中的lua代码有拼写错误

- Assets/Plugins/Slua_Managed/Helper.cs
- Assets/Plugins/Slua_Managed/LuaArray.cs
- Assets/Plugins/Slua_Managed/LuaObject.cs
- Assets/Plugins/Slua_Managed/LuaVarObject.cs
- Assets/Slua/Editor/LuaCodeGen.cs
- README.md
- standalone/msbuild_vs2012.bat
- standalone/premake.lua
- standalone/slua-standalone-tests/TestArray.cs
- standalone/slua-standalone-tests/TestProperty.cs
- standalone/slua-standalone-tests/TestSLua.cs
- standalone/vs2012/slua-standalone-tests.csproj
- standalone/vs2012/slua-standalone-tests.csproj.user
- standalone/vs2012/slua-standalone.csproj
- standalone/vs2012/slua-standalone.csproj.user
- standalone/vs2012/slua-standalone.sln
- standalone/vs2013/slua-standalone-tests.csproj
- standalone/vs2013/slua-standalone-tests.csproj.user
- standalone/vs2013/slua-standalone.csproj
- standalone/vs2013/slua-standalone.csproj.user
- standalone/vs2013/slua-standalone.sln
Try to add more power for slua to create C# array.  Fix 64bit number bugs.
> More Power for LuaVarObject

- Assets/Slua/Editor/LuaCodeGen.cs
fix WriteEvent method, it can generate the right checkType method for the value type now
> fix WriteEvent method, it can generate the right checkType method for the value type now

- Assets/Slua/Editor/CustomExport.cs
- Assets/Slua/example/HelloWorld.cs
fix compilation error in Unity 5.5
> fix compilation error in Unity 5.5

- Assets/Slua/Editor/LuaCodeGen.cs
ignore all components' constructor
> ignore all components' constructor

- Assets/Slua/Editor/LuaCodeGen.cs
support normal generic method:
`public void Test2<T>(T obj) where T:Object`
will be exported as 
`public void Test2<Object>(Object obj)`
This will helps exporting dotween or other scripts using a lot of template
> guess generic method

- Assets/Slua/Editor/LuaCodeGen.cs
Ref: http://qiankanglai.me/2016/11/27/unity-compiler/
> compile LuaObject into one dll

- Assets/Slua/Editor/LuaCodeGen.cs
统一 Generate() 和 GenerateUI() 过程，方便导出Unity中可选的服务性dll类的导出。同时增加
GenerateAds()。
> 统一 Generate() 和 GenerateUI() 过程

- Assets/Plugins/Slua_Managed/ObjectCache.cs
remove the non-existent variable "isArray"
> fix compile error when define symbol SLUA_CHECK_REFLECTION

- Assets/Plugins/Slua_Managed/LuaDLL.cs
Add a default parameter call for `lua_resume`
> Temp Fix  for Lua5.3

- Assets/Plugins/Slua_Managed/LuaValueType.cs
- Assets/Slua/Editor/LuaCodeGen.cs
- Assets/Slua/example/HelloWorld.cs
> 导出跟以有方法名重名的扩展方法时有bug

- Assets/Plugins/Slua_Managed/LuaObject.cs
- Assets/Plugins/Slua_Managed/LuaState.cs
- Assets/Plugins/Slua_Managed/LuaValueType.cs
- Assets/Slua/Editor/LuaCodeGen.cs
- Assets/Slua/example/ValueType.cs
> 将typePushMap移到LuaState实例中

- Assets/Slua/Editor/LuajitGen.cs
> bytecode编译

- Assets/Plugins/Slua_Managed/LuaState.cs
Just for convenience in Bugly: we can see the error stack and variables in one log 😺
> merge dump variable into errorReport

- Assets/Plugins/Slua_Managed/Logger.cs
- Assets/Slua/Editor/LoggerHelper.cs
- Assets/Slua/Editor/LoggerHelper.cs.meta
reference: http://www.xuanyusong.com/archives/3702
Check Logger when click rather than when Debug.Log
Also supports jumping to the excatly line with VSCode. Other IDEs need more investigation (opening file works fine but jumping line not working)
> Improved Logger

- build/make_ios.sh
that is not executable code :)
> "set development target to xxxx" in line 45 should be commented out

- Assets/Slua/Editor/LuaCodeGen.cs
1、fix the version of profiler api
2、fix the gc of checkEnum
> fix some problem

- Assets/Slua/Editor/LuaConsole.cs
Fix LuaConsole 'loadstring' in Lua53.
> Fix LuaConsole 'loadstring' in Lua53.
